### PR TITLE
fix: exit code wording

### PR DESCRIPTION
**Pull request by Stebalien**
The grammar was bugging me ("indicates a" instead of "indicates that a"), so I just removed "indicates" and cleaned up the wording a bit.

### CODE REVIEW

**Comment by mriise** [comment]
Frankly, removing `The` as well would sound better IMO.

**Comment by vyzo** [comment]
you guys are pathological...

**Comment by Stebalien** [comment]
> Frankly, removing The as well would sound better IMO.

Then it wouldn't be valid english.

**Comment by mriise** [comment]
That would be valid english though, right??

**Comment by Stebalien** [comment]
> edit: Actually this was legitimately something my english teacher encouraged us to avoid.

Using articles? No, no your english teacher did not tell you to avoid using articles.

**Comment by mriise** [comment]
They did! Granted they were fairly opinionated about writing in general and encouraged us to _avoid_ not disregard completely. Wikipeda has some good discussion of this https://en.wikipedia.org/wiki/English_articles, but I'm fairly confident that this is the case where there is no determiner required.

**Comment by Stebalien** [comment]
No, this definitely isn't the same thing.

- You _can_ drop the article at the beginning of a title, but these aren't titles.
- You _can_ drop the article for "contiguous" things. See "Message execution (including subcalls) used more gas than the specified limit."

**Review by mriise — APPROVED** [review]
Ok. As a personal preference I would omit "the" in a few places here, but this wouldn't follow the format of other documentation in the FVM. Ultimately this isn't an important change anyways.

**Pull request merged**
