### PR TITLE
fix: correctly convert `RegisteredPoStProof` type

### PR DESCRIPTION
**Pull request by 0x5459**

### CODE REVIEW

**Comment by hunjixin** [comment]
@Stebalien @raulk @anorth

**Review by arajasek — APPROVED** [review]

**Comment by anorth** [comment]
This suffix style, especially `V1P1`, makes it very hard to visually spot differences here. I suggest following up here and/or in the proofs library to find something a little more distinctive.

**Comment by zhiqiangxu** [comment]
> This suffix style, especially `V1P1`, makes it very hard to visually spot differences here. I suggest following up here and/or in the proofs library to find something a little more distinctive.

It would be even better if the codebase can stick to **the single point of reference principle**, say each module doesn't redefine what's essentially the same, but reference to the same one, this will eliminate such issue in the future and make the code more readable.

**Comment by arajasek** [comment]
@Stebalien No, we don't, they've landed in the right branches. Thanks SO MUCH again to @0x5459 and @hunjixin for the fix.

**Pull request closed without merging**
