### PR TITLE
Merge release/v2 into master

### PR DESCRIPTION
**Pull request by Stebalien**

### CODE REVIEW

**Comment by Stebalien** [comment]
So, plan:

- Merge this locally with `--strategy=ours`.
- In the future, continuously merge release/v2 into master.

This will let us make PRs against v2 and forward port them.

- **Pro**: Easier to maintain.
- **Con**: Duplicate commits due to the merge.

Thoughts?

**Comment by Stebalien** [comment]
Note: The _ideal_ solution would have been to put v3 changes in a feature branch... But that ship has sailed.

**Comment by Stebalien** [comment]
This just isn't worth it.

**Comment by jennijuju** [comment]
What’s happening here… anything I should be aware of?

**Comment by Stebalien** [comment]
Nothing. This was a no-op PR to merge release/v2 into master to make future ports easier (with a merge, rather than a cherry-pick). But it would have lead to messy history.

For now, I'm just going to cherry-pick.

**Pull request closed without merging**
