### PR TITLE
prototype for installation of user actors (including `install_actor` syscall)

### PR DESCRIPTION
**Pull request by vyzo**
This introduces the ability to deploy custom actors, in the manner specified in https://github.com/filecoin-project/ref-fvm/issues/444. Concretely:

- It adds an `install_actor` syscall that's only wired into the actor container if, and only if, the `m2-native` Cargo feature is enabled. This syscall won't be necessary for M2 EVM, that's why it's behind a feature flag.
- It adds the `IPLD_RAW` (0x55) codec to the allowlist for the IPLD subsystem.
- This still keeps compiled modules in memory.

Requires https://github.com/filecoin-project/builtin-actors/pull/216 to actually be useful.

### CODE REVIEW

**Review by raulk — COMMENTED** [review]
LGTM so far.

**Comment by vyzo** [comment]
rebased on master.

**Comment by vyzo** [comment]
Converted back to draft as #658 is a clean rebased form that has feature gating.

**Comment by raulk** [comment]
Superseded by #658.

**Pull request closed without merging**
