### PR TITLE
feat: add network version 18

### PR DESCRIPTION
**Pull request by Stebalien**
- And use it everywhere.
- And remove the test vectors until we get new ones.

### CODE REVIEW

**Review by vyzo — APPROVED** [review]

**Comment by jennijuju** [comment]
so we will need a name.. and I guess its gonna be......Candy or Crab? (cc @raulk )

**Comment by Stebalien** [comment]
> so we will need a name.. and I guess its gonna be......Candy or Crab? (cc @raulk )

nv18? Hygge!

**Comment by vyzo** [comment]
Can we merge this? i want.

**Comment by Stebalien** [comment]
Once the tests pass, yes. I also want this.

**Pull request merged**
