### PR TITLE
SDK: refactor: send should only return exit code and return data

### PR DESCRIPTION
**Pull request by arajasek**
More work towards #987 

`Send` now returns a `Response` comprising of an exitcode and an optional IpldBlock return.

### CODE REVIEW

**Review by Stebalien — APPROVED** [review]
`Response` or `Return` are likely reasonable names for a struct, but a tuple is also pretty reasonable.

**Comment by Stebalien** [comment]
So, looking at the other patches, it would be _really_ nice to introduce a named struct here to avoid a bunch of `ret.0` and `ret.1` lookups.

**Comment by arajasek** [comment]
> So, looking at the other patches, it would be _really_ nice to introduce a named struct here to avoid a bunch of `ret.0` and `ret.1` lookups.

Yeah, done, we now have a `Response`

**Review by anorth — COMMENTED** [review]
LGTM

**Pull request merged**
