### PR TITLE
Enable reporting of unreproducible crashers

### PR DESCRIPTION
**Pull request by Kubuxu**
fixes https://github.com/filecoin-project/ref-fvm/issues/959

### CODE REVIEW

**Comment by Stebalien** [comment]
@Kubuxu what needs to happen here?

**Comment by Kubuxu** [comment]
We need to figure out why the fuzzing CI reports unreproducible crashes for almost everything.

**Comment by Kubuxu** [comment]
https://github.com/filecoin-project/ref-fvm/issues/959

**Comment by Stebalien** [comment]
Ah, I see. Are you looking into it? Or should I put it on the roadmap?

**Comment by Kubuxu** [comment]
Right now I don't have much time to look deeper into it. So if you could put it on FVM's backlog it would be great.

**Pull request closed without merging**
