### PR TITLE
Clean up and simplify gas functionality

### PR DESCRIPTION
**Pull request by arajasek**
- Remove `verify_seal`, pretty sure this has been unused since pre-mainnet
- Replace the `charge_gas` syscall with a specialized `on_submit_verify_seal` call (better name welcome). This was the only use of the syscall in actors code, and I really don't like the idea of actors code asking the VM to charge arbitrary amounts of gas on a whim.

### CODE REVIEW

**Comment by raulk** [comment]
Agree with the removal of the charge_gas(units) syscall and the motivation for that, but the replacement is overly specific. One solution is to only inject this syscall in built-in actors. On the flip side, that creates precedent for a double standard when it comes to actors. I'd like to consider other possible solutions here like attempting to rejigger the syscall to move the gas calculation to the kernel.

**Comment by Stebalien** [comment]
> On the flip side, that creates precedent for a double standard when it comes to actors

This isn't the only place where we'll need to do this. At a minimum, we'll need to restrict some syscalls to the init actor.

I'd also like to restrict some of the miner syscalls, honestly (to reduce the attack surface area).

**Comment by raulk** [comment]
I've opened https://github.com/filecoin-project/ref-fvm/issues/468 to track a privilege system for syscalls. It isn't necessary for M1, though.

@arajasek could you scale back this PR to only remove the `verify_seal` pricelist item?

**Comment by raulk** [comment]
Based on discuission above, this is not something we'll merge. Final solution will come by way of https://github.com/filecoin-project/ref-fvm/issues/468 in M2.

**Pull request closed without merging**
