### PR TITLE
Ranged iteration on HAMTs

### PR DESCRIPTION
**Pull request by alexytsu**
With reference to the motivations discussed in https://github.com/filecoin-project/ref-fvm/issues/1514, this is the first part implementing ranged iteration functionality for HAMTs. The same basic concepts here can be applied to AMTs. 

A design tradeoff here is that it is up to the caller of `for_each_ranged` to guarantee that HAMT has not changed since the previous iteration. Actors which expose iteration over HAMTs are recommended to flush HAMTs before traversal and compare the root Cid to ensure contents have not changed.

### CODE REVIEW

**Review by anorth — APPROVED** [review]
Thank you @alexytsu! This looks good to me, but we should of course wait for some wider review from maintainers of these structures.

**Comment by Stebalien** [comment]
Why not just use the "next key"? This patch adds a new concept of "paths" which exposes internal structure. It should be pretty easy to seek to a specific key and start reading there.

> The same basic concepts here can be applied to AMTs.

AMTs are ordered, so they should _definitely_ just seek to the next index (i.e., don't apply the same concept).

**Comment by alexytsu** [comment]
Thanks for the review and suggestions @Stebalien 

> AMTs are ordered, so they should definitely just seek to the next index (i.e., don't apply the same concept).

Agreed. A method without externally exposed 'paths' was spiked in https://github.com/helix-onchain/ref-fvm/pull/2/files. I think this is more natural where keys are ordered. 

> Why not just use the "next key"? 

I like this idea because it additionally allows immediate feedback that the HAMT is exhausted. In the current algorithm, where the returned cursor points to the last item, it's not possible to tell if there are zero or more items left.

It's probably possible to hide the "path" concept from external users I'll put up a comparative implementation in a separate PR.

**Comment by alexytsu** [comment]
Replaced by https://github.com/filecoin-project/ref-fvm/pull/1665

**Pull request closed without merging**
